application: animmouse-website
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
    
- url: /about/
  static_files: public/about/index.html
  upload: public/about/index.html
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
    
- url: /css
  static_dir: public/css
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
  
- url: /js
  static_dir: public/js
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    
- url: /posts/
  static_files: public/posts/index.html
  upload: public/posts/index.html
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /posts
  static_files: public/posts/index.html
  upload: public/posts/index.html
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /posts/(.*)/
  static_files: public/posts/\1/index.html
  upload: public/posts/(.*)
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
    
- url: /projects/
  static_files: public/projects/index.html
  upload: public/projects/index.html
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /projects/(.*)/
  static_files: public/projects/\1/index.html
  upload: public/projects/(.*)
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /tags/
  static_files: public/tags/index.html
  upload: public/tags/index.html
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /tags/(.*)/
  static_files: public/tags/\1/index.html
  upload: public/tags/(.*)
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /(.*\.(ico|jpeg|jpg|png|svg|xml))
  static_files: public/\1
  upload: public/(.*\.(ico|jpeg|jpg|png|png|svg|xml))
    
- url: /site.webmanifest
  mime_type: application/manifest+json
  static_files: public/site.webmanifest
  upload: public/site.webmanifest
    
- url: /.*
  script: 404.php