baseurl: https://www.animmouse.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 10
title: Anim Mouse

DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
        - projects
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.ico

    footer:
        since: 2017
        customText: By Shawn M.

    dateFormat:
        published: January 02, 2006 03:04:05 PM MST
        lastUpdated: January 02, 2006 03:04:05 PM MST

    sidebar:
        emoji:
        subtitle: A person with interest and knowledge about computers.
        avatar:
            enabled: true
            local: true
            src: img/animmouse.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        giscus:
            repo: AnimMouse/animmouse-website
            repoID: MDEwOlJlcG9zaXRvcnkxOTE3NzcwODE=
            category: General
            categoryID: DIC_kwDOC25JOc4CBHiI
            mapping: pathname
            reactionsEnabled: 1
            emitMetadata: 0

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 10
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 15
        page:
            - type: toc

    opengraph:
        twitter:
            site: Anim_Mouse
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/AnimMouse
          params:
            icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/Anim_Mouse
          params:
            icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4