application: animmouse-website
version: 1
module: redirect
runtime: php55
api_version: 1
threadsafe: true
  
handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /.*
  script: index.php