name: Deploy Hugo Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          
      - name: Build Hugo
        run: hugo
        
      - name: Upload Website Source Code
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: ${{ github.workspace }}
          
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: www.animmouse.eu.org