name: Update Hugo Cloudflare Pages
on:
  workflow_call:
    inputs:
      variable_name:
        default: HUGO_VERSION
        type: string
      project_name:
        required: true
        type: string
      account_id:
        required: true
        type: string
    secrets:
      api_token:
        required: true
        
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Hugo latest version
        id: latest
        run: |
          version=$(gh api repos/gohugoio/hugo/releases/latest -q .tag_name)
          echo "version=${version#v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Get Hugo current version
        id: current
        uses: AnimMouse/Cloudflare-Pages-Variable-Action@v1
        with:
          method: get
          variable_name: ${{ inputs.variable_name }}
          project_name: ${{ inputs.project_name }}
          account_id: ${{ inputs.account_id }}
          api_token: ${{ secrets.api_token }}
          
      - name: Check if there is newer version
        run: '[[ "${{ steps.latest.outputs.version }}" != "${{ steps.current.outputs.variable_value }}" ]]'
        
      - name: Update Hugo version
        uses: AnimMouse/Cloudflare-Pages-Variable-Action@v1
        with:
          method: update
          variable_name: ${{ inputs.variable_name }}
          variable_value: ${{ steps.latest.outputs.version }}
          project_name: ${{ inputs.project_name }}
          account_id: ${{ inputs.account_id }}
          api_token: ${{ secrets.api_token }}